// <auto-generated />
namespace GAB2018.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class M201804210214 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M201804210214));
        
        string IMigrationMetadata.Id
        {
            get { return "201804202216336_M201804210214"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
